parameters:
  - name: AzureSubscription
    type: string

steps:
  - task: DownloadPipelineArtifact@2
    displayName: "Download DACPAC Artifact"
    inputs:
      source: "current"
      artifact: "DACPAC"
      path: $(Build.SourcesDirectory)/DACPAC

  - task: SqlAzureDacpacDeployment@1
    inputs:
      azureSubscription: SharedServicesPre
      AuthenticationType: "server"
      ServerName: $(RNW_DB_Server)
      DatabaseName: $(RNW_DB_Name)
      SqlUsername: $(RNW_DB_Deploy_SQLUser)
      SqlPassword: $(RNW_DB_Deploy_SQLPass)
      deployType: "DacpacTask"
      DeploymentAction: "Publish"
      IpDetectionMethod: "AutoDetect"
      DacpacFile: $(Build.SourcesDirectory)/DACPAC/UKHO.MaritimeSafetyInformation.Web.Database.dacpac

  - task: DownloadPipelineArtifact@2
    displayName: "Download App service Artifact"
    inputs:
      source: "current"
      artifact: "MaritimeSafetyInformation"
      path: $(Build.SourcesDirectory)/MaritimeSafetyInformation

  - task: FileTransform@2
    displayName: "File Transform: WebAppSettings"
    inputs:
      folderPath: '$(Pipeline.Workspace)/MaritimeSafetyInformation/*.zip'
      xmlTransformationRules:
      jsonTargetFiles: '**/appsettings.json'

  - task: AzureCLI@2
    displayName: "Integrating vNet with Web app"
    inputs:
      azureSubscription: "${{ parameters.AzureSubscription }}"
      scriptType: 'pscore'
      scriptLocation: 'scriptPath'
      scriptPath: '$(Pipeline.Workspace)/terraformartifact/webapp-vNet-integration.ps1'
      arguments: "-resourcegroup '$(webapp_rg)'
                  -webappname '$(WEB_APP_NAME)'
                  -vnetresourcegroupname '$(spokeRG)'
                  -vnetname '$(spokeVnetName)'
                  -subnetname '$(spokeSubnetName)'"

  - task: AzureWebApp@1
    displayName: "Azure App Deploy: msi-$(Environment)-webapp"
    inputs:
      azureSubscription: "${{ parameters.AzureSubscription }}"
      appType: webApp
      appName: "$(WEB_APP_NAME)"
      package: "$(Pipeline.Workspace)/MaritimeSafetyInformation/UKHO.MaritimeSafetyInformation.Web.zip"

  - task: PowerShell@2
    displayName: "Check the status of Service"
    inputs:
      targetType: filePath
      filePath: "$(Pipeline.Workspace)/terraformartifact/check_service_status.ps1"
      arguments: "-healthEndPointUrl $(MsiWafUrl)/health -waitTimeInMinute $(waitTimeInMinute)"

  - task: DownloadPipelineArtifact@2
    displayName: "Download Admin App service Artifact"
    inputs:
      source: "current"
      artifact: "MaritimeSafetyInformation"
      path: $(Build.SourcesDirectory)/MaritimeSafetyInformationAdmin

  - task: FileTransform@2
    displayName: "File Transform: Admin-WebAppSettings"
    inputs:
      folderPath: '$(Pipeline.Workspace)/MaritimeSafetyInformationAdmin/*.zip'
      xmlTransformationRules:
      jsonTargetFiles: '**/appsettings.json'

  - task: AzureWebApp@1
    displayName: "Azure App Deploy: msi-$(Environment)-Admin-webapp"
    inputs:
      azureSubscription: "${{ parameters.AzureSubscription }}"
      appType: webApp
      appName: "$(ADMIN_WEB_APP_NAME)"
      package: "$(Pipeline.Workspace)/MaritimeSafetyInformationAdmin/UKHO.MaritimeSafetyInformationAdmin.Web.zip"

  - task: PowerShell@2
    displayName: "Check the status of Admin Web App"
    inputs:
      targetType: filePath
      filePath: "$(Pipeline.Workspace)/terraformartifact/check_service_status.ps1"
      arguments: "-healthEndPointUrl $(Admin_DNS_URL)/health -waitTimeInMinute $(waitTimeInMinute)"
