parameters:
- name: SnykOnlyFailIfFixable
  type: boolean
  default: false
- name: SnykPassOnIssues
  type: boolean
  default: false

jobs:
- job: Snyk
  displayName: Run Snyk security scans
  pool: $(WindowsPool2)
  steps:
  - task: UseDotNet@2
    displayName: Use .NET SDK $(DotNetSdkVersion)
    inputs:
      packageType: sdk
      version: $(DotNetSdkVersion)

  - task: DotNetCoreCLI@2
    displayName: .NET - NuGet restore
    inputs:
      command: restore
      projects: |
        **/*.csproj
        !**/*Tests.csproj
      feedsToUse: config
      noCache: true
      nugetConfigPath: '$(Build.SourcesDirectory)\BuildNuget.config'
      workingDirectory: '$(Build.SourcesDirectory)\UKHO.MaritimeSafetyInformation.Web'

  - task: UkhoSnykScanTask@0
    displayName: Snyk IaC scan
    inputs:
      failOnIssues: ${{ not(parameters.SnykPassOnIssues) }}
      failOnThreshold: high
      organization: $(snykAbzuOrganizationId)
      serviceConnectionEndpoint: Snyk
      severityThreshold: low
      testType: iac
      monitorwhen: never
      ${{ if eq(parameters.SnykOnlyFailIfFixable, true) }}:
        additionalArguments: --fail-on=all

  - task: UkhoSnykScanTask@0
    displayName: Snyk SAST scan
    condition: succeededOrFailed()
    inputs:
      failOnIssues: ${{ not(parameters.SnykPassOnIssues) }}
      failOnThreshold: high
      organization: $(snykAbzuOrganizationId)
      serviceConnectionEndpoint: Snyk
      codeSeverityThreshold: low
      testType: code
      monitorwhen: never
      ${{ if eq(parameters.SnykOnlyFailIfFixable, true) }}:
        additionalArguments: --fail-on=all

  - task: UkhoSnykScanTask@0
    displayName: Snyk SCA scan
    condition: succeededOrFailed()
    inputs:
      failOnIssues: ${{ not(parameters.SnykPassOnIssues) }}
      failOnThreshold: high
      organization: $(snykAbzuOrganizationId)
      serviceConnectionEndpoint: Snyk
      codeSeverityThreshold: low
      testType: app
      monitorwhen: never
      severityThreshold: low
      ${{ if eq(parameters.SnykOnlyFailIfFixable, true) }}:
        additionalArguments: --all-projects --fail-on=all
      ${{ else }}:
        additionalArguments: --all-projects
