name: auto-patch-libman

on:
  schedule:
    - cron: '30 10 * * WED'
  workflow_dispatch:

jobs:
  update-libman:
    uses: UKHO/repo-auto-patch/.github/workflows/update-libman.yml@v1
    with:
      project-folder: "/UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformationAdmin.Web"
      libraries: "jquery,jquery-validate,jquery-validation-unobtrusive"
      work-item-title: "MSI - Auto-patch LibMan update"
      work-item-description: "Please review PR. Created by the auto-patch-libman action."
      work-item-tags: "Maritime Safety Information; TD2; Technical Debt"
    secrets:
      ado-pat: ${{ secrets.ADO_TOKEN }}
